### PR TITLE
Make Client satisfy ClientInterface

### LINKED ISSUE #124: *mailjet.Client does not satisfies mailjet.ClientInterface
```
*mailjet.Client does not implement mailjet.ClientInterface (wrong type for method Delete)
                have Delete(*mailjet.Request) (error)
                want Delete(*mailjet.Request, ...mailjet.RequestOptions) error
```

go.mod:
github.com/mailjet/mailjet-apiv3-go/v4 v4.0.7

go.sum:
github.com/mailjet/mailjet-apiv3-go/v4 v4.0.7 h1:Na8QAWN7g6VgAxK2fYPnbxQ7Vws2tE0hrb08oOhNNyw=
github.com/mailjet/mailjet-apiv3-go/v4 v4.0.7/go.mod h1:2SU3t6eh/uK6BSeBmdhpIUau99L4iPlIfbx4o4pAUQs=

### PR DESCRIPTION
**Pull request by dim13**
Fixes #124

### CODE REVIEW

File: mailjet_client.go [hunk 1]
```diff
@@ -194,9 +194,9 @@ func (c *Client) Put(fmr *FullRequest, onlyFields []string, options ...RequestOp
 }
 
 // Delete is used to delete a resource.
-func (c *Client) Delete(mr *Request) (err error) {
```
Comment (vtopc) [inline mailjet_client.go:197]: This appears to be a breaking change, and it seems that nobody has been using the `ClientInterface`, it's better to partly revert the https://github.com/mailjet/mailjet-apiv3-go/pull/87/files?w=1#diff-082e1ebd4516d127423accbad9ff46c1e3c31cd3270768f286d91ad887b006e1L19

Comment (dim13) [reply mailjet_client.go:197]: Given, that additional `options` is variadic it will not break any existing direct invocations of `Delete` method.

Comment (vtopc) [reply mailjet_client.go:197]: Oh, right.

**Review by vtopc — APPROVED** [review]

**Comment by vtopc** [comment]
Дякую.
